# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0024_auto_20161117_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms_with_dress', models.IntegerField(default=0, verbose_name='Bedrooms with dress')),
                ('bedrooms_with_closet', models.IntegerField(default=0, verbose_name='Bedrooms with closet')),
                ('complete_bathrooms', models.IntegerField(default=0, verbose_name='Complete bathrooms')),
                ('half_bathrooms', models.IntegerField(default=0, verbose_name='Half bathrooms')),
                ('living_room', models.BooleanField(default=False, verbose_name='Living room')),
                ('dinning_room', models.BooleanField(default=False, verbose_name='Dinning room')),
                ('beforedinning_room', models.BooleanField(default=False, verbose_name='Before dinning room')),
                ('integral_kitchen', models.BooleanField(default=False, verbose_name='Integral kitchen')),
                ('kitchen_cupboard', models.BooleanField(default=False, verbose_name='Cupboard kitchen')),
                ('study', models.BooleanField(default=False, verbose_name='Study')),
                ('bar', models.BooleanField(default=False, verbose_name='Bar')),
                ('cellar', models.BooleanField(default=False, verbose_name='Cellar')),
                ('tv_room', models.BooleanField(default=False, verbose_name='TV Room')),
                ('balcony', models.BooleanField(default=False, verbose_name='Balcony')),
                ('deck', models.BooleanField(default=False, verbose_name='Deck')),
                ('deck_with_gas_fireplace', models.BooleanField(default=False, verbose_name='Deck with gas fireplacek')),
                ('terrace', models.BooleanField(default=False, verbose_name='Terrace')),
                ('swimming_pool', models.BooleanField(default=False, verbose_name='Swimming Pool')),
                ('jacuzzi', models.BooleanField(default=False, verbose_name='Jacuzzi')),
                ('bathroom_with_tub', models.BooleanField(default=False, verbose_name='Bathroom with tub')),
                ('game_room', models.BooleanField(default=False, verbose_name='Game room')),
                ('guest_room', models.BooleanField(default=False, verbose_name='Guest room')),
                ('guest_bathroom', models.BooleanField(default=False, verbose_name='Guest bathroom')),
                ('interior_garden', models.BooleanField(default=False, verbose_name='Interior garden')),
                ('service_yard', models.BooleanField(default=False, verbose_name='Service yard')),
                ('room_service', models.BooleanField(default=False, verbose_name='Room service')),
                ('floor_heating_system', models.BooleanField(default=False, verbose_name='Floor heating system')),
                ('warehouse', models.BooleanField(default=False, verbose_name='Warehouse')),
                ('water_glass', models.IntegerField(default=0, verbose_name='Water glass')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
    ]
