# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_service_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='service_bathroom',
            field=models.BooleanField(default=False, verbose_name='Service Bathroom'),
        ),
    ]
