# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='Elevator'),
        ),
    ]
