# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_auto_20161119_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Ofice', 'verbose_name_plural': 'Offices'},
        ),
    ]
