# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms_with_dress', models.CharField(max_length=50, verbose_name='Bedrooms with dress')),
                ('bedrooms_with_closet', models.CharField(max_length=50, verbose_name='Bedrooms with closet')),
                ('complete_bathrooms', models.CharField(max_length=50, verbose_name='Complete bathrooms')),
                ('half_bathrooms', models.CharField(max_length=50, verbose_name='Half bathrooms')),
                ('living_room', models.CharField(max_length=50, verbose_name='Living room')),
                ('dinning_room', models.CharField(max_length=50, verbose_name='Dinning room')),
                ('kitchen', models.CharField(max_length=50, verbose_name='Kitchen')),
                ('linen_closet', models.CharField(max_length=50, verbose_name='Linen closet')),
                ('service_yard', models.CharField(max_length=50, verbose_name='Service yard')),
                ('garden', models.CharField(max_length=50, verbose_name='Garden')),
                ('roof_garden', models.CharField(max_length=50, verbose_name='Roof garden')),
                ('terrace', models.CharField(max_length=50, verbose_name='Terrace')),
                ('parking_places', models.CharField(max_length=50, verbose_name='Parking places')),
                ('ground_m2', models.CharField(max_length=50, verbose_name='M2 Ground')),
                ('construction_m2', models.CharField(max_length=50, verbose_name='M2 Ground')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Departament',
                'verbose_name_plural': 'Departaments',
            },
        ),
    ]
