# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='construction_m2',
        ),
        migrations.RemoveField(
            model_name='departament',
            name='ground_m2',
        ),
    ]
