# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0003_auto_20161002_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='garden',
            field=models.BooleanField(default=False, verbose_name='Garden'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='parking_places',
            field=models.CharField(default=0, max_length=50, verbose_name='Parking places'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='roof_garden',
            field=models.BooleanField(default=False, verbose_name='Roof garden'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='service_yard',
            field=models.BooleanField(default=False, verbose_name='Service yard'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='terrace',
            field=models.BooleanField(default=False, verbose_name='Terrace'),
        ),
    ]
