# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0004_auto_20161002_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='parking_places',
        ),
        migrations.RemoveField(
            model_name='departament',
            name='roof_garden',
        ),
    ]
