# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0006_auto_20161013_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='bedrooms_with_closet',
            field=models.IntegerField(default=0, verbose_name='Bedrooms with closet'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='bedrooms_with_dress',
            field=models.IntegerField(default=0, verbose_name='Bedrooms with dress'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='complete_bathrooms',
            field=models.IntegerField(default=0, verbose_name='Complete bathrooms'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='half_bathrooms',
            field=models.IntegerField(default=0, verbose_name='Half bathrooms'),
        ),
    ]
