# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0008_auto_20161013_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='room_service',
            field=models.BooleanField(default=False, verbose_name='Room service'),
        ),
        migrations.AddField(
            model_name='departament',
            name='study',
            field=models.BooleanField(default=False, verbose_name='Study'),
        ),
        migrations.AddField(
            model_name='departament',
            name='tv_room',
            field=models.BooleanField(default=False, verbose_name='TV Room'),
        ),
    ]
