# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0009_auto_20161117_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='lock_off',
            field=models.BooleanField(default=False, verbose_name='Lock Off'),
        ),
        migrations.AddField(
            model_name='departament',
            name='one_room',
            field=models.BooleanField(default=False, verbose_name='One Room'),
        ),
        migrations.AddField(
            model_name='departament',
            name='penthouse',
            field=models.BooleanField(default=False, verbose_name='Penthouse'),
        ),
        migrations.AddField(
            model_name='departament',
            name='three_rooms',
            field=models.BooleanField(default=False, verbose_name='Three Rooms'),
        ),
        migrations.AddField(
            model_name='departament',
            name='two_rooms',
            field=models.BooleanField(default=False, verbose_name='Two Rooms'),
        ),
    ]
