# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departaments', '0010_auto_20191205_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='studio',
            field=models.BooleanField(default=False, verbose_name='Studio'),
        ),
    ]
