# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Source'),
        ),
    ]
