# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('photo', models.ImageField(upload_to=b'project_photos', verbose_name='Photo')),
                ('brief_description', models.TextField(max_length=140, verbose_name='Brief description')),
                ('description', models.TextField(max_length=140, verbose_name='Description')),
                ('category', models.CharField(choices=[(b'departament', 'Departamento'), (b'office', 'Office'), (b'house - room', 'House - Room')], max_length=30, verbose_name='Category')),
                ('status', models.CharField(choices=[(b'sale', 'Sale'), (b'pre-sale', 'Pre-sale'), (b'sold', 'Sold'), (b'in construction', 'In construction'), (b'finished', 'Finished')], max_length=30, verbose_name='Category')),
                ('google_maps_link', models.URLField()),
                ('ground_m2', models.CharField(max_length=50, verbose_name='M2 Ground')),
                ('construction_m2', models.CharField(max_length=50, verbose_name='M2 Ground')),
                ('video', models.URLField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('photo', models.ImageField(upload_to=b'project_banner_photos', verbose_name='Photo')),
                ('description', models.TextField(max_length=140, verbose_name='Description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Banner',
                'verbose_name_plural': 'Project Banners',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'project_banner_photos', verbose_name='Photo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Photo',
                'verbose_name_plural': 'Project Photos',
            },
        ),
    ]
