# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'project_brochures', verbose_name='File')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Brochure',
                'verbose_name_plural': 'Brochures',
            },
        ),
    ]
