# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160806_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='file', upload_to=b'project_logos', verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='construction_m2',
            field=models.CharField(max_length=50, verbose_name='M2 Construction'),
        ),
    ]
