# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160810_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_2',
            field=models.CharField(choices=[(b'current projects', 'Current projects'), (b'completed projects', 'Completed projects')], default='current projects', max_length=30, verbose_name='Status 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[(b'departament', 'Departament'), (b'office', 'Office'), (b'house - room', 'House - Room'), (b'commercial', 'Commercial'), (b'fractionation', 'Fractionation')], max_length=30, verbose_name='Category'),
        ),
    ]
