# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160810_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status_2',
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[(b'current projects', 'Current projects'), (b'completed projects', 'Completed projects')], default='current projects', max_length=30, verbose_name='Project status'),
            preserve_default=False,
        ),
    ]
