# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160823_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(b'current projects', 'Current projects'), (b'completed projects', 'Completed projects')], default='current projects', max_length=30, verbose_name='Project type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(verbose_name='Video'),
        ),
    ]
