# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160831_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbanner',
            name='description',
            field=models.TextField(max_length=40, verbose_name='Description'),
        ),
    ]
