# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160904_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
    ]
