# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(b'current projects', 'Current projects'), (b'completed projects', 'Completed projects')], max_length=30, verbose_name='Project type'),
        ),
        migrations.AlterField(
            model_name='projectbanner',
            name='description',
            field=models.TextField(max_length=140, verbose_name='Description'),
        ),
    ]
