# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20160914_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='google_maps_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Video'),
        ),
    ]
