# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20160919_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ground_m2',
            field=models.TextField(verbose_name='M2 Ground'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
