# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20161002_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.TextField(default=b'', verbose_name='Address'),
        ),
    ]
