# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about_image',
            field=models.ImageField(default='', upload_to=b'project_photos', verbose_name='About image'),
            preserve_default=False,
        ),
    ]
