# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'project_logos', verbose_name='Logo'),
        ),
    ]
