# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20161117_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='club_house',
            field=models.BooleanField(default=False, verbose_name='Club house'),
        ),
    ]
