# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20161117_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='building',
            field=models.CharField(choices=[('Departaments', 'Departaments'), ('Offices', 'Offices'), ('Houses', 'Houses')], default='Departaments', max_length=30, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
