# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_project_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='building',
            field=models.CharField(choices=[('departaments', 'Departaments'), ('offices', 'Offices'), ('houses', 'Houses')], max_length=30, verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_departaments',
            field=models.IntegerField(default=0, verbose_name='Departaments or houses'),
        ),
    ]
