# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20161118_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='Elevador'),
        ),
    ]
