# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_project_elevator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(max_length=200, verbose_name='Meta descripcion')),
                ('keywords', models.TextField(verbose_name='Keywords')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
    ]
