# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_seodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seodata',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='meta_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Meta descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='T\xedtulo'),
        ),
    ]
