# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20170115_2036'),
    ]

    def set_project_slug(apps, schema_editor):
        Project = apps.get_model("projects", "Project")
        for project in Project.objects.all():
            project.slug = slugify(project.name)
            project.save()

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),

        migrations.RunPython(set_project_slug),
    ]
