# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-05 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20191124_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimming_pool', models.BooleanField(default=False, verbose_name='Swimming Pool')),
                ('jacuzzi', models.BooleanField(default=False, verbose_name='Jacuzzi')),
                ('water_mirror', models.BooleanField(default=False, verbose_name='Water Mirror')),
                ('gym', models.BooleanField(default=False, verbose_name='Gym')),
                ('yoga_area', models.BooleanField(default=False, verbose_name='Yoga Area')),
                ('rooftop', models.BooleanField(default=False, verbose_name='Rooftop')),
                ('roofgarden', models.BooleanField(default=False, verbose_name='Roofgarden')),
                ('grill_area', models.BooleanField(default=False, verbose_name='Grill Area')),
                ('waiting_area', models.BooleanField(default=False, verbose_name='Waiting Area')),
                ('reading_area', models.BooleanField(default=False, verbose_name='Reading Area')),
                ('bicycle_area', models.BooleanField(default=False, verbose_name='Bicycle Area')),
                ('extra_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Extra 1')),
                ('extra_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Extra 2')),
                ('extra_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Extra 3')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Amenities',
                'verbose_name_plural': 'Projects Amenities',
            },
        ),
    ]
