# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_projectamenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectamenities',
            name='photo',
            field=models.ImageField(default='1', upload_to=b'project_photos', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
