# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-12 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_projectamenities_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbanner',
            name='mobile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'project_banner_photos', verbose_name='Mobile Photo'),
        ),
        migrations.AddField(
            model_name='projectbanner',
            name='tablet_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'project_banner_photos', verbose_name='Tablet Photo'),
        ),
    ]
