# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20191212_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mobile',
            field=models.ImageField(blank=True, null=True, upload_to=b'project_photos', verbose_name='Foto Celular'),
        ),
        migrations.AddField(
            model_name='project',
            name='tablet',
            field=models.ImageField(blank=True, null=True, upload_to=b'project_photos', verbose_name='Foto Tablet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to=b'project_photos', verbose_name='Foto Escritorio'),
        ),
        migrations.AlterField(
            model_name='projectbanner',
            name='photo',
            field=models.ImageField(upload_to=b'project_banner_photos', verbose_name='Desktop Photo'),
        ),
    ]
